### ISSUE TITLE
WithdrawToCryptoAsync  Exception 

### ISSUE THREAD

**Issue by GITMIKRO** [dougdellolio/coinbasepro-csharp#123]
```
var withdrawalqty = 6.22;
var WithdrawToWallet = "3L81bL8************************9fMySKzk2hck";
var currencyType = Currency.BTC;     
var sandbox = true;
var authenticator = new GDAXSharp.Network.Authentication.Authenticator(apikey, secretkey, passphrase);
var gdaxClient = new GDAXClient(authenticator, sandbox);

var result = await gdaxClient.WithdrawalsService.WithdrawToCryptoAsync(WithdrawToWallet, withdrawalqty, currencyType)
```
The above returns the following: 
 GDAXSharp.Exceptions.GDAXSharpHttpException: Invalid scope
   at GDAXSharp.Services.AbstractService.<SendHttpRequestMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GDAXSharp.Services.AbstractService.<SendServiceCall>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at GDAXSharp.Services.Withdrawals.WithdrawalsService.<WithdrawToCryptoAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult(

Sandbox API keys have "transfer" permissions

Thx for any suggestions.

**Comment by Sotam** [comment]
I guess the problem is the sandbox.

**Comment by GITMIKRO** [comment]
I will test on the live API and update here with my results.

**Comment by GITMIKRO** [comment]
Thank you @Sotam , you were correct. Apparently, the sandbox method through the wrapper does not seem to have the capability to emulate a withdrawal.  I used the live API for a test, and now I am having a different issue.  Seems that the CB-2FA-TOKEN header is required, although GDAX is specific on their website (and within their API docs) that when creating the API keys, the Transfer Permissions bypass 2FA requirements.  On the website, next to the checkbox to enable transfer permissions when creating a new API Key, it says "Transfer (CAUTION: will bypass 2FA. See docs for more details.)"

Here is the response I get when using the API wrapper:

GDAXSharp.Exceptions.GDAXSharpHttpException: Two factor authentication is enabled, CB-2FA-TOKEN header is required
   at GDAXSharp.Services.AbstractService.<SendHttpRequestMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GDAXSharp.Services.AbstractService.<SendServiceCall>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at GDAXSharp.Services.Withdrawals.WithdrawalsService.<WithdrawToCryptoAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Thanks for any suggestions.

**Comment by dougdellolio** [comment]
this is a weird one....i would think checking that box would bypass the 2FA but it isn't.

I was able to get this to work by adding the header manually here with my 2FA code: 
https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXSharp/Network/HttpRequest/HttpRequestMessageService.cs#L59

i did something like this:
`httpRequestMessage.Headers.Add("CB-2FA-Token", "<2FAcode>");`

the code changes frequently so this is obviously not a viable solution. I am going to reach out to GDAX and see if they can provide any more explanation here.

**Comment by GITMIKRO** [comment]
ok Thx.

**Comment by BradForsythe** [comment]
I saw the same problem, it seems that GDAX is not allowing fund transfers without 2FA regardless of their check box.

**Comment by dougdellolio** [comment]
> We had some reports of issues with permissions but our engineering team has just rolled out a fix for that. With your new key, you should be able to have normal access.

that was the response I received (surprisingly fast) so try it out now and see if it works. they also mentioned to try generating a new key if you're using an older one from last month. let me know

**Comment by GITMIKRO** [comment]
@dougdellolio 
@BradForsythe 
This worked on the first try. Didn't need to gen a new key. 
Thx!
