### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by LeonardoX77** [dougdellolio/coinbasepro-csharp#179]
Hi Doug
Sometimes CoinbasPro library breaks in my production server due to an unhandled error in Supersocket library that I can't reproduce on my local environment, and probably it's an error that should be posted on Supersocket repo issues, but I'm not sure if Supersocket owner could say that the error is caused by anything in between your CoinbasePro implementation. So I decided to post it here to get some support from you that help to resolve this issue.
This is is the stack trace:
Framework version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at SuperSocket.ClientEngine.TcpClientSession.Connect(System.Net.EndPoint)
   at WebSocket4Net.WebSocket.Open()
   at CoinbasePro.WebSocket.WebSocketFeed.Open()
   at CoinbasePro.WebSocket.WebSocket.Start(System.Collections.Generic.List`1<CoinbasePro.Shared.Types.ProductType>, System.Collections.Generic.List`1<CoinbasePro.WebSocket.Types.ChannelType>, System.Nullable`1<Int32>)
   at CoinbasePro.WebSocket.WebSocket.WebSocket_Closed(System.Object, System.EventArgs)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at WebSocket4Net.WebSocket.client_Error(System.Object, SuperSocket.ClientEngine.ErrorEventArgs)
   at SuperSocket.ClientEngine.ClientSession.OnError(System.Exception)
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(System.Net.Sockets.Socket, System.Object, System.Net.Sockets.SocketAsyncEventArgs, System.Exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(System.Object, System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Exception, Int32, System.Net.Sockets.SocketFlags)
   at System.Net.Sockets.MultipleConnectAsync.AsyncFail(System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.Fail(Boolean, System.Exception)
   at System.Net.Sockets.MultipleConnectAsync.DoDnsCallback(System.IAsyncResult, Boolean)
   at System.Net.Sockets.MultipleConnectAsync.DnsCallback(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Dns.ResolveCallback(System.Object)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

As you can see, CoinbasePro is involved between SuperSocket.ClientEngine.ClientSession.OnError event and WebSocket4Net.WebSocket.Open() method, but I don't know how to get the exception from OnError event. I have read [log configuration](http://docs.supersocket.net/v1-6/en-US/Logging-in-SuperSocket) but I don't know how to enable it in my app.config or if it's even possible.

Maybe [this issue](https://github.com/kerryjiang/SuperSocket/issues/157) could be related, but I'm not sure.

Also I'm trying to avoid unhandled exceptions implementing [this code](https://stackify.com/catch-unhandled-exceptions-csharp/), but it doesn't work, at least for this case.

**Comment by dougdellolio** [comment]
@LeonardoX77 hard to say from that stack trace 😞. have you tried subscribing to `OnWebSocketError`? https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/WebSocket/WebSocket.cs#L332) there may be some more information about the exception there

**Comment by LeonardoX77** [comment]
Hi Doug
Thanks for your quick replace. Yes, I've subscribed to both OnWebSocketError and OnErrorReceived, but I had an error logging the error, so I've fixed it and waiting for the issue to be reproduced again, but I found also this log (logged at same time as previous error):

System.Exception: The socket is connecting, cannot connect again!
   at SuperSocket.ClientEngine.TcpClientSession.Connect(EndPoint remoteEndPoint)
   at WebSocket4Net.WebSocket.Open()
   at CoinbasePro.WebSocket.WebSocketFeed.Open()
   at CoinbasePro.WebSocket.WebSocket.Start(List`1 productTypes, List`1 channelTypes, Nullable`1 autoSendPingInterval)
   at CoinbasePro.WebSocket.WebSocket.WebSocket_Closed(Object sender, EventArgs e)
   at WebSocket4Net.WebSocket.FireClosed()
   at WebSocket4Net.WebSocket.OnClosed()
   at WebSocket4Net.WebSocket.client_Error(Object sender, ErrorEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnError(Exception e)
   at SuperSocket.ClientEngine.TcpClientSession.ProcessConnect(Socket socket, Object state, SocketAsyncEventArgs e, Exception exception)
   at SuperSocket.ClientEngine.ConnectAsyncExtension.SocketAsyncEventCompleted(Object sender, SocketAsyncEventArgs e)

It seems that after WebSocket_Closed you're trying to connect again but the SuperSocket.ClientEngine is already connecting, maybe cause there's more than one thread?

**Comment by chrisw000** [comment]
I've never seen this sort of error.... however, Coinbase will close the socket at their end, if there is no activity for what appears to be something like 60 seconds. 

When Coinbase close the socket this code will try to re-open it - which it seems to be doing from your stacktrace.

In order to not have Coinbase close the socket in the first place.... startup with an autoping value

You're probably doing something like this:

`client.WebSocket.Start(productIds, channels);`

do this instead
`_client.WebSocket.Start(productIds, channels, 30);`

Hopefully that will stop Coinbase from closing the socket, and therefore you'll avoid whatever this error is?
