### ISSUE TITLE
Json Issue: Error converting value "" to type 'System.Guid'.

### ISSUE THREAD

**Issue by nemesiswes** [dougdellolio/coinbasepro-csharp#184]
Just recently out of nowhere I get the error shown below in my console output.

```
Socket Opened = System.EventArgs
Websocket Error Event = System.IO.IOException: The read operation failed, see inner exception. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "" to type 'System.Guid'. Path 'client_oid', line 1, position 163. ---> System.ArgumentException: Could not cast or convert from System.String to System.Guid.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CoinbasePro.WebSocket.WebSocket.WebSocket_MessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.FireMessageReceived(String message)
   at WebSocket4Net.Command.Text.ExecuteCommand(WebSocket session, WebSocketCommandInfo commandInfo)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at WebSocket4Net.WebSocket.client_DataReceived(Object sender, DataEventArgs e)
   at SuperSocket.ClientEngine.ClientSession.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.OnDataRead(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.StartRead()
Socket Opened = System.EventArgs
An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in System.dll
Error converting value "" to type 'System.Guid'. Path 'client_oid', line 1, position 163.
```

It just started happening recently with no code changes on my end that would cause it.
I tried different versions going back to 1.0.23, nothing works.

It seems like a issue with Coinbase since it just started happening out of nowhere. 

I'm going to try a fresh project and see it still happens, but in the mean time, maybe you already know how to fix it. I thought about going and modifying Newton soft to get it to work again but that is kinda my last resort.

**Comment by nemesiswes** [comment]
Yep, Just started a fresh project and using  .NET 4.6.1 and the latest Nuget Package 1.0.25.
Here is what I get:

`Trader Started
Socket Opened
snapshot recieved
Ticker  = 3341.73000000
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
L2U recieved
An unhandled exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in System.dll
Error converting value "" to type 'System.Guid'. Path 'client_oid', line 1, position 163.`

I just made some simple callbacks telling me if they were called, hence the l2u, ticker etc. It gives the same error as before even on a fresh install using latest packages.

**Comment by dougdellolio** [comment]
@nemesiswes i am seeing this now too...... weird. I believe this is on Coinbase side but either way I have added a way to handle it here #185
